# Generated by Django 4.2.3 on 2023-07-11 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_ropa_alter_boleta_numero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='tipoproducto',
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='descripcion'),
        ),
        migrations.AddField(
            model_name='producto',
            name='nombreprod',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='nombre del producto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='porcentajedesc',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
