# Generated by Django 4.2.3 on 2023-07-11 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_producto_marca_remove_producto_tipoproducto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stockprod',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
