# Generated by Django 4.2.3 on 2023-07-11 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_producto_stockprod_alter_producto_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='porcentajedesc',
        ),
        migrations.AddField(
            model_name='producto',
            name='descuento_oferta',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='descuento_subscriptor',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
